### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by zjuchenyuan** [xhacker/zju-jwb-to-icalendar#4]
https://github.com/zjuchenyuan/zju-jwb-to-icalendar

make a lot of changes, author includes Liu Gengming and me.

Deployed using Aliyun Function Compute, Aliyun API Gateway and Upyun CDN.

Here is the link:

[https://api.py3.io/jwbtools.html](https://api.py3.io/jwbtools.html)

Thanks for your initial commit, do you consider a PR request?

**Comment by xhacker** [comment]
Great work! But the changes seem too big to merge. I can mention your project in the README.

**Comment by xhacker** [comment]
Done.
